pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                //sh 'mvn -B -DskipTests clean package'
                echo "Step Build"
            }
        }
        stage('Test') {
            steps {
                //sh 'mvn test'
                echo "Step Test"
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
                //sh './jenkins/scripts/deliver.sh'
                echo 'Step Deliver'
            }
        }
    }
}
